package com.sungkunn.inam.model

data class Market(var name: String? = "",
                  var owner: String? = "",
                  var phone: String? = "",
                  var line: String? = "",
                  var facebook: String? = "",
                  var email: String? = "",
                  var address: String? = "",
                  var latitude: String? = "",
                  var longitude: String? = "",
                  var monday_open: String? = "",
                  var monday_close: String? = "",
                  var tuesday_open: String? = "",
                  var tuesday_close: String? = "",
                  var wednesday_open: String? = "",
                  var wednesday_close: String? = "",
                  var thursday_open: String? = "",
                  var thursday_close: String? = "",
                  var friday_open: String? = "",
                  var friday_close: String? = "",
                  var saturday_open: String? = "",
                  var saturday_close: String? = "",
                  var sunday_open: String? = "",
                  var sunday_close: String? = "") {
}